language: ruby

cache: bundler

install:
  # Install Jekyll and dependencies
  - bundle install

gemfile: docs/Gemfile

script:
  - bundle exec rake site:deploy --quiet

branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4

 # Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'

env:
  global:
    secure: "Vt0ML6h+ZK9DQJmLx+I7uMe6HvqnOGMT0xZ6JRiQh43ur1WlBOMFtC7R2vbe6GHUTiH28H3WctYp3Tc42eXtK5bnMXgMIEilJ75sCTfNpkdIWcHda+06nGxjA02RmA7Ur1Xn4RvZXUMr21NuzcPI4pXn75kk7ppt71ysbS+J2kfg/Hg7DaqJoKyHqz648/aEgtkwp4CJ5+dw5ezOQIjoCZW/iB67Tj8pYazl4CzxXjYXw2G3Wjnh0WSOw63fDlMkcG4rEr+/WUSSVyXMIOIbf3XbQwrh9JzZiqz1tcChicbET+JycZuJ7NXlQnfBDj8sKTqaAgdt0DPGoZojwPvsCop0YTvD4wd92NPCIDnJn6K95c33J62mJ793ZYWOeBiZkytPS3A3JAzGyYLUsWjhvHSXAdPu214McopVA13LILMzvHBVieJ9vpg+/yX7NbF0szC2tlz0MvHvns32ps+K7OjkwkDUys37A0QI7GSmli3PbbwZg5ME0RBtMFJHDW6GxvqwDCB9cc1svpDGag4eT4bFPB+nUT65msSGRRKqS30UWErPygIopy3hf/yg7iQIcZ9SKIAOX2NvsJtq6aJlOAwtRM6n1QOETvefJ4pGg+ZUq6RacoucReu34CiO9Qj5XR7BJkSCZaxId0orsax74H1Sg5YhqAwTLw9K2xHQ6WY"
    